### ISSUE TITLE
fizzbuzz with if, for

### ISSUE THREAD

**Issue by kateseunghyunkim** [kateseunghyunkim/fizzbuzz#1]
## Task

 - [x] for statement (range : 1 to 15)
 - [x] print fizz if i is times of 3
 - [x] print buzz if i is times of 5 
 - [x] print fizzbuzz if i is times of 15

**Comment by kateseunghyunkim** [comment]
good
